# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=150, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='FilmLibraryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('temporal_coverage_start', models.IntegerField(blank=True, null=True)),
                ('temporal_coverage_end', models.IntegerField(blank=True, null=True)),
                ('catalog_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('countries', models.ManyToManyField(to='records.Country')),
                ('directors', models.ManyToManyField(to='records.Director')),
            ],
            options={
                'db_table': 'film_library_records',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='filmlibraryrecord',
            name='keywords',
            field=models.ManyToManyField(to='records.Keyword'),
        ),
    ]
