# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlibraryrecord',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmlibraryrecord',
            name='trailer_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
