# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180523_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibraryrecord',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='records.Keyword'),
        ),
    ]
