# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180523_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibraryrecord',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='records.Keyword'),
        ),
    ]
