# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20190228_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlibraryrecord',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
    ]
